//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CD_Sync_Portable.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CD_Sync_Portable.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap appIcon_48x48x32 {
            get {
                object obj = ResourceManager.GetObject("appIcon_48x48x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("back_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back_32x32x32 {
            get {
                object obj = ResourceManager.GetObject("back_32x32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back_48x48x32 {
            get {
                object obj = ResourceManager.GetObject("back_48x48x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blankcd {
            get {
                object obj = ResourceManager.GetObject("blankcd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browser_refresh_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("browser_refresh_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browser_refresh_24x24x32 {
            get {
                object obj = ResourceManager.GetObject("browser_refresh_24x24x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browser_root_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("browser_root_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browser_root_32x32x32 {
            get {
                object obj = ResourceManager.GetObject("browser_root_32x32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browser_up_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("browser_up_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browser_up_24x24x32 {
            get {
                object obj = ResourceManager.GetObject("browser_up_24x24x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap configure_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("configure_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap configure_24x24x32 {
            get {
                object obj = ResourceManager.GetObject("configure_24x24x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cross_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("cross_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cross1_32x32x32 {
            get {
                object obj = ResourceManager.GetObject("cross1_32x32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap del_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("del_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap del_32x32x32 {
            get {
                object obj = ResourceManager.GetObject("del_32x32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_description_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("edit_description_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap explore_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("explore_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap explore_16x16x321 {
            get {
                object obj = ResourceManager.GetObject("explore_16x16x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap explore_32x32x32 {
            get {
                object obj = ResourceManager.GetObject("explore_32x32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap explore_in_main_window_32x32x32 {
            get {
                object obj = ResourceManager.GetObject("explore_in_main_window_32x32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap export_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("export_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appConfig.xml.
        /// </summary>
        internal static string fileConfigXML {
            get {
                return ResourceManager.GetString("fileConfigXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cdsync_export.xml.
        /// </summary>
        internal static string fileExportedImagesXML {
            get {
                return ResourceManager.GetString("fileExportedImagesXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageCategories.xml.
        /// </summary>
        internal static string fileImageCategoriesXML {
            get {
                return ResourceManager.GetString("fileImageCategoriesXML", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FillDownHS {
            get {
                object obj = ResourceManager.GetObject("FillDownHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FillRightHS {
            get {
                object obj = ResourceManager.GetObject("FillRightHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forward_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("forward_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forward_32x32x32 {
            get {
                object obj = ResourceManager.GetObject("forward_32x32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forward_48x48x32 {
            get {
                object obj = ResourceManager.GetObject("forward_48x48x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hardDiskOffline_48x48x32 {
            get {
                object obj = ResourceManager.GetObject("hardDiskOffline_48x48x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hardDiskOffline_64x64x32 {
            get {
                object obj = ResourceManager.GetObject("hardDiskOffline_64x64x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hardDiskOffline_96x96x32 {
            get {
                object obj = ResourceManager.GetObject("hardDiskOffline_96x96x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hardDiskOnline_48x48x32 {
            get {
                object obj = ResourceManager.GetObject("hardDiskOnline_48x48x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hardDiskOnline_64x64x32 {
            get {
                object obj = ResourceManager.GetObject("hardDiskOnline_64x64x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hardDiskOnline_96x96x32 {
            get {
                object obj = ResourceManager.GetObject("hardDiskOnline_96x96x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("help_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image_delete_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("image_delete_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image_delete_32x32x32 {
            get {
                object obj = ResourceManager.GetObject("image_delete_32x32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image_properties_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("image_properties_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap import_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("import_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve selected multiple objects. Please select a single object to view its properties..
        /// </summary>
        internal static string introTextExtendedPropertiesMultiSelect {
            get {
                return ResourceManager.GetString("introTextExtendedPropertiesMultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No object selected. Selected an object in the browser to view its properties here..
        /// </summary>
        internal static string introTextExtendedPropertiesPanelNothingSelected {
            get {
                return ResourceManager.GetString("introTextExtendedPropertiesPanelNothingSelected", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon main_icon {
            get {
                object obj = ResourceManager.GetObject("main_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string msgAreYouSure {
            get {
                return ResourceManager.GetString("msgAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while connecting to the VFS (Virtual File System) for this image..
        /// </summary>
        internal static string msgCannotConnectToVFS {
            get {
                return ResourceManager.GetString("msgCannotConnectToVFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file couldn&apos;t be deleted. Please enter a different filename..
        /// </summary>
        internal static string msgCannotOverwrite {
            get {
                return ResourceManager.GetString("msgCannotOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination folder you&apos;ve selected is not accessible. Either it doesn&apos;t exist or you don&apos;t have sufficient privileges to access it..
        /// </summary>
        internal static string msgDestinationFolderInAccessible {
            get {
                return ResourceManager.GetString("msgDestinationFolderInAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination path cannot be empty..
        /// </summary>
        internal static string msgDestinationPathEmpty {
            get {
                return ResourceManager.GetString("msgDestinationPathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory was not found..
        /// </summary>
        internal static string msgDirectoryNotFound {
            get {
                return ResourceManager.GetString("msgDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error opening help..
        /// </summary>
        internal static string msgErrorOpeningHelp {
            get {
                return ResourceManager.GetString("msgErrorOpeningHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There wan an error retrieving critical application settings from the configuration file. This may indicate a corrupt configuration file. The application will now exit..
        /// </summary>
        internal static string msgErrorRetrievingCriticalSettings {
            get {
                return ResourceManager.GetString("msgErrorRetrievingCriticalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving applications settings from the configuration file. Some of the features may not work properly..
        /// </summary>
        internal static string msgErrorRetrievingSettings {
            get {
                return ResourceManager.GetString("msgErrorRetrievingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD Sync Portable encountered an error saving application settings. Your changes may be lost..
        /// </summary>
        internal static string msgErrorSavingSettings {
            get {
                return ResourceManager.GetString("msgErrorSavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of existing images in the export directory is not in a correct format. Therefore, you cannot add more images to the list. Do you still want to continue using this directory? Doing so will delete the existing list. Click &apos;No&apos; to go back and select a different directory..
        /// </summary>
        internal static string msgExistingExportFileCorrupt {
            get {
                return ResourceManager.GetString("msgExistingExportFileCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export was successful!.
        /// </summary>
        internal static string msgExportSuccessful {
            get {
                return ResourceManager.GetString("msgExportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name cannot be an empty string..
        /// </summary>
        internal static string msgFileNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("msgFileNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name cannot be empty..
        /// </summary>
        internal static string msgImageCategoryNameEmpty {
            get {
                return ResourceManager.GetString("msgImageCategoryNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new image has been successfully created!.
        /// </summary>
        internal static string msgImageCreated {
            get {
                return ResourceManager.GetString("msgImageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files/folders were added to the image. You may need to review your filteration settings..
        /// </summary>
        internal static string msgImageEmpty {
            get {
                return ResourceManager.GetString("msgImageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image name cannot be empty..
        /// </summary>
        internal static string msgImageNameEmpty {
            get {
                return ResourceManager.GetString("msgImageNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory you have specified to hold your images is invalid. Either it does not exist, or you do not have sufficient privilege to access it..
        /// </summary>
        internal static string msgImagesDirectoryInvalid {
            get {
                return ResourceManager.GetString("msgImagesDirectoryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder you have specified as the image source does not exist. Please select a different source location..
        /// </summary>
        internal static string msgImageSourceNotFound {
            get {
                return ResourceManager.GetString("msgImageSourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source you selected is not ready. Make sure that there is a disk in the drive..
        /// </summary>
        internal static string msgImageSourceNotReady {
            get {
                return ResourceManager.GetString("msgImageSourceNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a source for this image..
        /// </summary>
        internal static string msgImageSourceNotSpecified {
            get {
                return ResourceManager.GetString("msgImageSourceNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source of this image is not available. Make sure that the source disk is in the drive and then click the &apos;Refresh&apos; button..
        /// </summary>
        internal static string msgImageSourceOffline {
            get {
                return ResourceManager.GetString("msgImageSourceOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory you have selected does not contain any images to import..
        /// </summary>
        internal static string msgImportDirectoryEmpty {
            get {
                return ResourceManager.GetString("msgImportDirectoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error getting the list of images from the directory you selected..
        /// </summary>
        internal static string msgImportListRetrieveFailed {
            get {
                return ResourceManager.GetString("msgImportListRetrieveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import was successful!.
        /// </summary>
        internal static string msgImportSuccessful {
            get {
                return ResourceManager.GetString("msgImportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory you have selected contains a list of exported images, but it is not in a correct format..
        /// </summary>
        internal static string msgImportXMLInvalid {
            get {
                return ResourceManager.GetString("msgImportXMLInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A filename cannot contain any of the following characters: \ / : * ? &quot; &lt; &gt; |.
        /// </summary>
        internal static string msgInvalidFileName {
            get {
                return ResourceManager.GetString("msgInvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access the image. The VFS file for the image is invalid..
        /// </summary>
        internal static string msgInvalidVFS {
            get {
                return ResourceManager.GetString("msgInvalidVFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected a filename to save the filelist to. Click the Browse button to select a filename..
        /// </summary>
        internal static string msgNoFileNameSpecified {
            get {
                return ResourceManager.GetString("msgNoFileNameSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected any images to export..
        /// </summary>
        internal static string msgNoImageSelectedToExport {
            get {
                return ResourceManager.GetString("msgNoImageSelectedToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected any images to import..
        /// </summary>
        internal static string msgNoImageSelectedToImport {
            get {
                return ResourceManager.GetString("msgNoImageSelectedToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected any images to search..
        /// </summary>
        internal static string msgNoImageSelectedToSearch {
            get {
                return ResourceManager.GetString("msgNoImageSelectedToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search complete. No items matching the specified criteria were found..
        /// </summary>
        internal static string msgNoSearchResults {
            get {
                return ResourceManager.GetString("msgNoSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter something to search for. You can also use wildcards..
        /// </summary>
        internal static string msgNothingToSearch {
            get {
                return ResourceManager.GetString("msgNothingToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error updating the picture for this image..
        /// </summary>
        internal static string msgPictureUpdateError {
            get {
                return ResourceManager.GetString("msgPictureUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart the application for the changes to take effect..
        /// </summary>
        internal static string msgRestartRequired {
            get {
                return ResourceManager.GetString("msgRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A search is already active. You must wait for the current search to finish before starting a new one..
        /// </summary>
        internal static string msgSearchActive_NewSearch {
            get {
                return ResourceManager.GetString("msgSearchActive_NewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A search is currently active. If you close this window, the search will be cancelled. Do you want to close the window and cancel the search?.
        /// </summary>
        internal static string msgSearchActive_WindowClosing {
            get {
                return ResourceManager.GetString("msgSearchActive_WindowClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source path you selected does not contain any files/folders..
        /// </summary>
        internal static string msgSourceEmpty {
            get {
                return ResourceManager.GetString("msgSourceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate not specified..
        /// </summary>
        internal static string msgSpecifyBitrate {
            get {
                return ResourceManager.GetString("msgSpecifyBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size not specified..
        /// </summary>
        internal static string msgSpecifyFileSize {
            get {
                return ResourceManager.GetString("msgSpecifyFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample rate not specified..
        /// </summary>
        internal static string msgSpecifySampleRate {
            get {
                return ResourceManager.GetString("msgSpecifySampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! An exception occured and I could not handle it. Now, I have to close. I have created an error report and saved it to the file &apos;errLog.log&apos; in the application&apos;s installation directory. Please, send an email to the author at ankitr.42@gmail.com, describing what you were doing when this problem crept up. Attach the error report with the email, so that the problem can be fixed..
        /// </summary>
        internal static string msgUnhandledExceptionOccured {
            get {
                return ResourceManager.GetString("msgUnhandledExceptionOccured", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap netDriveOffline_48x48x32 {
            get {
                object obj = ResourceManager.GetObject("netDriveOffline_48x48x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap netDriveOffline_64x64x32 {
            get {
                object obj = ResourceManager.GetObject("netDriveOffline_64x64x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap netDriveOffline_96x96x32 {
            get {
                object obj = ResourceManager.GetObject("netDriveOffline_96x96x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap netDriveOnline_48x48x32 {
            get {
                object obj = ResourceManager.GetObject("netDriveOnline_48x48x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap netDriveOnline_64x64x32 {
            get {
                object obj = ResourceManager.GetObject("netDriveOnline_64x64x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap netDriveOnline_96x96x32 {
            get {
                object obj = ResourceManager.GetObject("netDriveOnline_96x96x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_image_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("new_image_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_image_24x24x32 {
            get {
                object obj = ResourceManager.GetObject("new_image_24x24x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_image_32x32x32 {
            get {
                object obj = ResourceManager.GetObject("new_image_32x32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap opticalDiskOffline_48x48x32 {
            get {
                object obj = ResourceManager.GetObject("opticalDiskOffline_48x48x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap opticalDiskOffline_64x64x32 {
            get {
                object obj = ResourceManager.GetObject("opticalDiskOffline_64x64x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap opticalDiskOffline_96x96x32 {
            get {
                object obj = ResourceManager.GetObject("opticalDiskOffline_96x96x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap opticalDiskOnline_48x48x32 {
            get {
                object obj = ResourceManager.GetObject("opticalDiskOnline_48x48x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap opticalDiskOnline_64x64x32 {
            get {
                object obj = ResourceManager.GetObject("opticalDiskOnline_64x64x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap opticalDiskOnline_96x96x32 {
            get {
                object obj = ResourceManager.GetObject("opticalDiskOnline_96x96x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string promptAreYouSure {
            get {
                return ResourceManager.GetString("promptAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is not yet complete. Are you sure you want to cancel?.
        /// </summary>
        internal static string promptCancel {
            get {
                return ResourceManager.GetString("promptCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected image category will be deleted permanently and member images will be moved to the deleted categories group. Proceed?.
        /// </summary>
        internal static string promptImageCategoryDelete {
            get {
                return ResourceManager.GetString("promptImageCategoryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected image will be permanently deleted. Proceed?.
        /// </summary>
        internal static string promptImageDelete {
            get {
                return ResourceManager.GetString("promptImageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not specified a description for this image. Proceed?.
        /// </summary>
        internal static string promptImageDescEmpty {
            get {
                return ResourceManager.GetString("promptImageDescEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not specified a picture for this image. Proceed?.
        /// </summary>
        internal static string promptImagePicEmpty {
            get {
                return ResourceManager.GetString("promptImagePicEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the images belong to deleted categories. Do you want them to be moved to the Uncategorized Images group? You can also change their category individually as desired..
        /// </summary>
        internal static string promptImagesInDeletedCategory {
            get {
                return ResourceManager.GetString("promptImagesInDeletedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you still want to keep the image?.
        /// </summary>
        internal static string promptKeepImage {
            get {
                return ResourceManager.GetString("promptKeepImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All images that belong to this category will be permanently deleted. Proceed?.
        /// </summary>
        internal static string promptMemberImagesDelete {
            get {
                return ResourceManager.GetString("promptMemberImagesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like the memeber images to be moved to the new category?.
        /// </summary>
        internal static string promptMoveImagesToNewCategory {
            get {
                return ResourceManager.GetString("promptMoveImagesToNewCategory", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap properties_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("properties_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap properties_32x32x32 {
            get {
                object obj = ResourceManager.GetObject("properties_32x32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RAMDisk {
            get {
                object obj = ResourceManager.GetObject("RAMDisk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap removableDrive {
            get {
                object obj = ResourceManager.GetObject("removableDrive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap removableDriveOffline_48x48x32 {
            get {
                object obj = ResourceManager.GetObject("removableDriveOffline_48x48x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap removableDriveOffline_64x64x32 {
            get {
                object obj = ResourceManager.GetObject("removableDriveOffline_64x64x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap removableDriveOffline_96x96x32 {
            get {
                object obj = ResourceManager.GetObject("removableDriveOffline_96x96x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap removableDriveOnline_48x48x32 {
            get {
                object obj = ResourceManager.GetObject("removableDriveOnline_48x48x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap removableDriveOnline_64x64x32 {
            get {
                object obj = ResourceManager.GetObject("removableDriveOnline_64x64x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap removableDriveOnline_96x96x32 {
            get {
                object obj = ResourceManager.GetObject("removableDriveOnline_96x96x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("search_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_32x32x32 {
            get {
                object obj = ResourceManager.GetObject("search_32x32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_48x48x32 {
            get {
                object obj = ResourceManager.GetObject("search_48x48x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search1_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("search1_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search1_32x32x32 {
            get {
                object obj = ResourceManager.GetObject("search1_32x32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tick_16x16x32 {
            get {
                object obj = ResourceManager.GetObject("tick_16x16x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unknownOffline_48x48x32 {
            get {
                object obj = ResourceManager.GetObject("unknownOffline_48x48x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unKnownOffline_64x64x32 {
            get {
                object obj = ResourceManager.GetObject("unKnownOffline_64x64x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unKnownOffline_96x96x32 {
            get {
                object obj = ResourceManager.GetObject("unKnownOffline_96x96x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unKnownOnline_48x48x32 {
            get {
                object obj = ResourceManager.GetObject("unKnownOnline_48x48x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unKnownOnline_64x64x32 {
            get {
                object obj = ResourceManager.GetObject("unKnownOnline_64x64x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unKnownOnline_96x96x32 {
            get {
                object obj = ResourceManager.GetObject("unKnownOnline_96x96x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
